Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookStoreWeb.Data;
using BookStoreWeb.Helper;
using BookStoreWeb.Models;
using BookStoreWeb.Models.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;

namespace BookStoreWeb.Controllers
{
    public class CartController : Controller
    {
        private readonly DataContext dataContext;

        public CartController(DataContext dataContext)
        {
            this.dataContext = dataContext;
        }

        [Route("Index")]
        public IActionResult Index(CheckOutModel model)
        {
            var cart = SessionHelper.GetObjectFromJson<List<ProductToCart>>(HttpContext.Session, "cart");
            ViewBag.cart = cart;
            if (cart != null)
            {
                ViewBag.total = cart.Sum(item => item.ProductModel.ProductPrice * item.Quantity);
            }
            return View(model);
        }

        [Route("buy/{id}")]
        public IActionResult Buy(int id)
        {

            if (SessionHelper.GetObjectFromJson<List<ProductToCart>>(HttpContext.Session, "cart") == null)
                {
                // Kiem tra gio hang co null hay ko
                Product p = dataContext.Products.Find(id);  //Lay ra ID cua san pham <3
                List<ProductToCart> cart = new List<ProductToCart>();
                cart.Add(new ProductToCart
                {
                    // Add san pham vo Cart
                    ProductModel = new ProductModel()
                    {
                        ProductId = p.ProductId,
                        ProductName = p.ProductName,
                        ProductImage = p.ProductImage,
                        ProductPrice = p.ProductPrice,
                    },
                    Quantity = 1
                });
                SessionHelper.SetObjectAsJson (HttpContext.Session, "cart", cart);
            }
            else
            {
                //Gio hang ko null thi tang gia tri gio hang len theo tung san pham Add
                List<ProductToCart> cart = SessionHelper.GetObjectFromJson<List<ProductToCart>>(HttpContext.Session, "cart");
                int index = isExist(id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    Product p = dataContext.Products.Find(id);
                    cart.Add(new ProductToCart
                    {
                        ProductModel = new ProductModel()
                        {
                            ProductId = p.ProductId,
                            ProductName = p.ProductName,
                            ProductImage = p.ProductImage,
                            ProductPrice = p.ProductPrice
                        },
                        Quantity=1,
                    });
                }

                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToAction("Index");
        }

        [Route("remove/{id}")]
        public IActionResult Remove(int id)
        {
            List<ProductToCart> cart = SessionHelper.GetObjectFromJson<List<ProductToCart>>(HttpContext.Session, "cart");
            int index = isExist(id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction("Index");
        }
        private int isExist(int id)
        {
            List<ProductToCart> cart = SessionHelper.GetObjectFromJson<List<ProductToCart>>(HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].ProductModel.ProductId == id)
                {
                    return i;
                }
            }
            return -1;
        }

        public IActionResult CheckOut()
        {
            
            var cart = SessionHelper.GetObjectFromJson<List<ProductToCart>>(HttpContext.Session, "cart");
            ViewBag.cart = cart;
            ViewBag.total = cart.Sum(item => item.ProductModel.ProductPrice * item.Quantity);
            cart.Clear();
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return View();
        }

        [HttpPost]
        public IActionResult CheckOut(CheckOutModel model)
        {
            // Kiểm tra nếu chưa đăng nhập, trả về trang login
            if (HttpContext.Session.GetInt32("UserID") == null)
            {
                return RedirectToAction("Login", "Accounts");
            }

            
            // Nếu chưa nhập đủ sđt và địa chỉ thì quay lại
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index", model);
            }

            // Tính % còn lại sau khi sale
            double sale = 1;
            if (CheckDiscount(model.DiscountCode) != -1)
            {
                sale = (100 - CheckDiscount(model.DiscountCode)) / 100;
            }

            var cart = SessionHelper.GetObjectFromJson<List<ProductToCart>>(HttpContext.Session, "cart");
            HttpContext.Session.Remove("cart");

            var order = new Order()
            {
                DateTime = DateTime.UtcNow,
                UserId = HttpContext.Session.GetInt32("UserID").GetValueOrDefault(),
                TotalPrice = cart.Sum(item => item.ProductModel.ProductPrice * item.Quantity) * sale,
                Address = model.Address,
                Phone = model.PhoneNumber
            };

            foreach (var item in cart)
            {
                var orderDetail = new OrderDetail()
                {
                    Quantity = item.Quantity,
                    Amount = item.Quantity * item.ProductModel.ProductPrice,
                    ProductId = item.ProductModel.ProductId
                };
                order.OrderDetails.Add(orderDetail);
            }

            dataContext.Orders.Add(order);
            dataContext.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        // Action kiểm tra mã giảm giá hợp lệ
        [HttpPost]
        public double CheckDiscount(string Code)
        {
            var discount = dataContext.Discounts.FirstOrDefault(x => x.Name == Code);
            if (discount != null &&
                discount.QuantityDiscount > 0 &&
                discount.CreatDate <= DateTime.Now &&
                discount.DateValid > DateTime.Now)
            {
                return discount.Percent;
            } 
            return -1;
        }
    }

}

Controllers/DetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookStoreWeb.Data;
using BookStoreWeb.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookStoreWeb.Controllers
{
    public class DetailController : Controller
    {
        private readonly DataContext dataContext;

        public DetailController(DataContext dataContext)
        {
            this.dataContext = dataContext;
        }
             
        [HttpGet ("Detail/(id)/(name)")]
        public IActionResult Index(int id)
        {
            ProductModel productModel = new ProductModel();
            var p = dataContext.Products.Where(m => m.ProductId == id).FirstOrDefault();
            if (p==null)
            {
                return View(id);
            }
            else
            {
                productModel.ProductId = p.ProductId;
                productModel.ProductName = p.ProductName;
                productModel.ProducQuantity = p.ProducQuantity;
                productModel.Tacgia = p.Tacgia;
                productModel.NXB = p.NXB;
                productModel.Nhacungcap = p.Nhacungcap;
                productModel.ProductPrice = p.ProductPrice;
                productModel.ProductImage = p.ProductImage;
                productModel.Description = p.Description;

            }
            return View(productModel);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BookStoreWeb.Models;
using BookStoreWeb.Data;
using BookStoreWeb.Models.Domain;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.EntityFrameworkCore;

namespace BookStoreWeb.Controllers
{
    public class HomeController : Controller
    {
        //private readonly ILogger<HomeController> _logger;
        ProductData product;
        DataContext data;

        public HomeController(ProductData productData, DataContext dataContext)
        {
            this.product = productData;
            this.data = dataContext;


        }


        //public HomeController(ILogger<HomeController> logger)
        //{
        //    _logger = logger;
        //}

        //public IActionResult Index()
        //{
        //    return View(data.ProductList);
        //}

        public IActionResult Index()
        {
            List<ProductModel> products = new List<ProductModel>();
            List<Product> productss = data.Products.ToList();

            foreach ( var item in productss)
            {
                products.Add(new ProductModel()
                {
                    ProductId=item.ProductId,
                    ProductName=item.ProductName,
                    ProducQuantity=item.ProducQuantity,
                    Tacgia=item.Tacgia,
                    NXB= item.NXB,
                    Nhacungcap=item.Nhacungcap,
                    ProductPrice=item.ProductPrice,
                    ProductImage=item.ProductImage,
                    Description=item.Description
                });
            }
            return View(products);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public IActionResult SearchItem(string searchname)
        {
            var product = data.Products.FirstOrDefault(m => m.ProductName == searchname);

            return View(product);

            //return RedirectToAction("SearchItem", "Home");
        }

        public IActionResult Sort()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Sort(string sort)
        {
            var list = data.Products.ToList();

            if (sort == "Giá giảm dần")
            {
                //list.OrderBy(m => m.ProductPrice);
                list = data.Products.FromSqlRaw<Product>(@"select * from Products p order by p.ProductPrice desc").ToList();
                return View(list);
            }
            if (sort == "Giá tăng dần")
            {
                list = data.Products.FromSqlRaw<Product>(@"select * from Products p order by p.ProductPrice").ToList();
                return View(list);
            }
            if (sort == "Tên A-Z")
            {
                list = data.Products.FromSqlRaw<Product>(@"select * from Products p order by p.ProductName").ToList();
                return View(list);
            }
            if (sort == "Tên Z-A")
            {
                list = data.Products.FromSqlRaw<Product>(@"select * from Products p order by p.ProductName desc").ToList();
                return View(list);
            }

            return View(list);
        }
    }
}

Views/Home/SearchItem.cshtml
@model BookStoreWeb.Models.Domain.Product


@{
    ViewData["Title"] = "SearchModel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <h3>Kết quả tìm kiếm của bạn : </h3>
<br />

<div class="col-lg-3 col-md-6 mb-4">

    <div class="card h-100">
        <div class="card-img-top">
            <div class="img">
                <img src="~/image/@Html.DisplayFor(m => m.ProductImage)" alt="" />
                <div class="txt">
                    <a href="#"><h3 style="color:aliceblue">MUA NGAY</h3></a>
                    <a asp-controller="Detail" asp-action="Index" asp-route-id="@Html.DisplayFor(m=>m.ProductId)" asp-route-name="@Html.DisplayFor(m=>m.ProductName)"><h3 style="color:aliceblue">XEM CHI TIẾT</h3></a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <h4 class="card-title">@Html.DisplayFor(m => m.ProductName) </h4>
            <p style="font-size: 20px;color: sandybrown" class="card-text">@Html.DisplayFor(m => m.ProductPrice)&nbsp; đ </p>
        </div>
    </div>
</div>

@*giao dien cua cart item*@

<style>
   
    .img {
        position: relative;
        overflow: hidden;
    }

    .txt {
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.52);
        position: absolute;
        bottom: 50px;
        text-align: center;
        padding: 10px;
        box-sizing: border-box;
        opacity: 0;
    }

    .img:hover div.txt {
        opacity: 1;
        transform: translateY(50px);
        transition: ease-in-out 0.5s;
    }

    .img:hover img {
        transform: scale(1.5);
        transition: all ease-in-out 0.5s;
    }
</style>

Views/Home/Sort.cshtml
@model List<BookStoreWeb.Models.Domain.Product>
@{
    ViewData["Title"] = "Sort";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3> Kết quả sắp xếp :</h3>
<br />
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-lg-3 col-md-6 mb-4">

            <div class="card h-100">
                <div class="card-img-top">
                    <div class="img">
                        <img src="~/image/@item.ProductImage" alt="">
                        <div class="txt">
                            <a asp-controller="Cart" asp-action="Buy" asp-route-id="@item.ProductId"><h3 style="color:aliceblue">MUA NGAY</h3></a>
                            <a asp-controller="Detail" asp-action="Index" asp-route-id="@item.ProductId" asp-route-name="@item.ProductName"><h3 style="color:aliceblue">XEM CHI TIẾT</h3></a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <h4 class="card-title">@item.ProductName </h4>
                    <p style="        font-size: 20px;color: sandybrown" class="card-text">@item.ProductPrice&nbsp; đ &nbsp;&nbsp;<img src="~/image/hot-icon-1-1.gif" style="width: 45px; height: 30px" /></p>
                </div>
            </div>
        </div>}
</div>

@*giao dien cua cart item*@

<style>

    .img {
        position: relative;
        overflow: hidden;
    }

    .txt {
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.52);
        position: absolute;
        bottom: 50px;
        text-align: center;
        padding: 10px;
        box-sizing: border-box;
        opacity: 0;
    }

    .img:hover div.txt {
        opacity: 1;
        transform: translateY(50px);
        transition: ease-in-out 0.5s;
    }

    .img:hover img {
        transform: scale(1.5);
        transition: all ease-in-out 0.5s;
    }
</style>