Controllers/ManageUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookStoreWeb.Data;
using BookStoreWeb.Models.Domain;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;

namespace BookStoreWeb.Controllers
{
    public class ManageUserController : BaseController
    {
        DataContext data;
        public ManageUserController(DataContext dataContext)
        {
            this.data = dataContext;
        }
        public IActionResult Index()
        {
            var list = data.Users.FromSqlRaw<Users>(@"select * from Users u where u.Status = 'Active' and u.UserId > 1").ToList();
            return View(list);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Users user)
        {
            using (var dbtran = data.Database.BeginTransaction())
            {
                try
                {
                    var temp = data.Users.FirstOrDefault(m => m.Email == user.Email);
                    if (temp == null)
                    {
                        if (user.Password == user.ConfirmPassword)
                        {
                            user.Status = "Active";
                            user.CreatUser = "Admin";
                            user.CreatDate = DateTime.Now;
                            user.EditUser = "Admin";
                            user.EditDate = DateTime.Now;

                            data.Users.Add(user);
                            data.SaveChanges();
                            dbtran.Commit();
                            return RedirectToAction("Index");
                        }
                    }
                    else
                    {
                        dbtran.Rollback();
                        return View(user);
                    }
                }
                catch (Exception ex)
                {
                    dbtran.Rollback();
                    ModelState.AddModelError("", "" + ex.Message);

                    return View(user);
                }
            }
            return View(user);
        }

        public IActionResult Edit(int? id)
        {
            var editUser = data.Users.FirstOrDefault(m => m.UserId == id);
            return View(editUser);
        }

        [HttpPost]
        public IActionResult Edit(Users user)
        {
            var editUser = data.Users.FirstOrDefault(m => m.UserId == user.UserId);

            editUser.EditUser = "Admin";
            editUser.EditDate = DateTime.Now;
            editUser.FirstName = user.FirstName;
            editUser.LastName = user.LastName;

            data.Entry(editUser).State = EntityState.Modified;
            data.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Detail(int? id)
        {
            var detailUser = data.Users.FirstOrDefault(m => m.UserId == id);
            return View(detailUser);
        }

        public IActionResult Delete(int id)
        {
            var deleteRow = data.Users.FirstOrDefault(m => m.UserId == id);
            deleteRow.Status = "Deactive";
            deleteRow.EditUser = "Admin";
            deleteRow.EditDate = DateTime.Now;

            data.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Views/ManageUser/Create.cshtml
@model BookStoreWeb.Models.Domain.Users

@{
    ViewData["Title"] = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <h3>Thêm mới</h3>

<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm())
        {
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"> Tên :</label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"> Họ :</label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"> Email :</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Password" class="control-label"> Mật Khẩu :</label>
                <input type="password" asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ConfirmPassword" class="control-label">Nhập Lại Mật Khẩu :</label>
                <input type="password" asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>

            if (ViewBag.Error != null)
            {
                <div style="color: red; font-size: 20px;">@ViewBag.Error</div>
            }

            <br />
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        }
    </div>
</div>

Views/ManageUser/Edit.cshtml
@model BookStoreWeb.Models.Domain.Users

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <h3>Chỉnh sửa</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="UserId" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/ManageUser/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <h3>Quản Lí Người Dùng</h3>
@model List<BookStoreWeb.Models.Domain.Users>

<p><a class="btn btn-primary" asp-controller="ManageUser" asp-action="Create">Add</a></p>
<table class="table table-bordered table-striped">
    <thead>
        <tr style="font-size: 18px" class="table-primary">
            <td>Id</td>
            <td>Họ</td>
            <td>Tên</td>
            <td>Email</td>
            <td>PassWord</td>
            <td>Ngày tạo</td>
            <td>Người tạo</td>
            <td>Ngày chỉnh</td>
            <td>Người chỉnh</td>

            <td></td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@item.UserId</td>
            <td>@item.FirstName</td>
            <td>@item.LastName</td>
            <td>@item.Email</td>
            <td>@item.Password</td>
            <td>@item.CreatDate</td>
            <td>@item.CreatUser</td>
            <td>@item.EditDate</td>
            <td>@item.EditUser</td>
            <td>
                <a class="btn btn-outline-info" asp-controller="ManageUser" asp-action="Edit" asp-route-id="@item.UserId">Edit</a>
                <a class="btn btn-outline-danger" asp-controller="ManageUser" asp-action="Delete" asp-route-id="@item.UserId">Delete</a>
            </td>
        </tr>

        }
    </tbody>
</table>